// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message-payload.proto

package com.ziggurat.proto;

public final class MessagePayloadProto {
  private MessagePayloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessagePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ziggurat.proto.MessagePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes message = 1;</code>
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>string topic_entity = 2;</code>
     */
    java.lang.String getTopicEntity();
    /**
     * <code>string topic_entity = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicEntityBytes();

    /**
     * <code>int32 retry_count = 3;</code>
     */
    int getRetryCount();

    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    boolean hasMetadata();
    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getMetadata();
    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder getMetadataOrBuilder();
  }
  /**
   * Protobuf type {@code com.ziggurat.proto.MessagePayload}
   */
  public  static final class MessagePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ziggurat.proto.MessagePayload)
      MessagePayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePayload.newBuilder() to construct.
    private MessagePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePayload() {
      message_ = com.google.protobuf.ByteString.EMPTY;
      topicEntity_ = "";
      retryCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessagePayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              message_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topicEntity_ = s;
              break;
            }
            case 24: {

              retryCount_ = input.readInt32();
              break;
            }
            case 34: {
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder subBuilder = null;
              if (metadata_ != null) {
                subBuilder = metadata_.toBuilder();
              }
              metadata_ = input.readMessage(com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metadata_);
                metadata_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Builder.class);
    }

    public interface MetadataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ziggurat.proto.MessagePayload.Metadata)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string topic = 1;</code>
       */
      java.lang.String getTopic();
      /**
       * <code>string topic = 1;</code>
       */
      com.google.protobuf.ByteString
          getTopicBytes();

      /**
       * <code>int64 timestamp = 2;</code>
       */
      long getTimestamp();

      /**
       * <code>int32 partition = 3;</code>
       */
      int getPartition();
    }
    /**
     * Protobuf type {@code com.ziggurat.proto.MessagePayload.Metadata}
     */
    public  static final class Metadata extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ziggurat.proto.MessagePayload.Metadata)
        MetadataOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Metadata.newBuilder() to construct.
      private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Metadata() {
        topic_ = "";
        timestamp_ = 0L;
        partition_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Metadata(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                topic_ = s;
                break;
              }
              case 16: {

                timestamp_ = input.readInt64();
                break;
              }
              case 24: {

                partition_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder.class);
      }

      public static final int TOPIC_FIELD_NUMBER = 1;
      private volatile java.lang.Object topic_;
      /**
       * <code>string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        }
      }
      /**
       * <code>string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 2;
      private long timestamp_;
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      public static final int PARTITION_FIELD_NUMBER = 3;
      private int partition_;
      /**
       * <code>int32 partition = 3;</code>
       */
      public int getPartition() {
        return partition_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getTopicBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
        }
        if (timestamp_ != 0L) {
          output.writeInt64(2, timestamp_);
        }
        if (partition_ != 0) {
          output.writeInt32(3, partition_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTopicBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
        }
        if (timestamp_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, timestamp_);
        }
        if (partition_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, partition_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata)) {
          return super.equals(obj);
        }
        com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata other = (com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata) obj;

        boolean result = true;
        result = result && getTopic()
            .equals(other.getTopic());
        result = result && (getTimestamp()
            == other.getTimestamp());
        result = result && (getPartition()
            == other.getPartition());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
        hash = (37 * hash) + PARTITION_FIELD_NUMBER;
        hash = (53 * hash) + getPartition();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.ziggurat.proto.MessagePayload.Metadata}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ziggurat.proto.MessagePayload.Metadata)
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_Metadata_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder.class);
        }

        // Construct using com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          topic_ = "";

          timestamp_ = 0L;

          partition_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor;
        }

        public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getDefaultInstanceForType() {
          return com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.getDefaultInstance();
        }

        public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata build() {
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata buildPartial() {
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata result = new com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata(this);
          result.topic_ = topic_;
          result.timestamp_ = timestamp_;
          result.partition_ = partition_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata) {
            return mergeFrom((com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata other) {
          if (other == com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.getDefaultInstance()) return this;
          if (!other.getTopic().isEmpty()) {
            topic_ = other.topic_;
            onChanged();
          }
          if (other.getTimestamp() != 0L) {
            setTimestamp(other.getTimestamp());
          }
          if (other.getPartition() != 0) {
            setPartition(other.getPartition());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object topic_ = "";
        /**
         * <code>string topic = 1;</code>
         */
        public java.lang.String getTopic() {
          java.lang.Object ref = topic_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            topic_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string topic = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTopicBytes() {
          java.lang.Object ref = topic_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            topic_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string topic = 1;</code>
         */
        public Builder setTopic(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          topic_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string topic = 1;</code>
         */
        public Builder clearTopic() {
          
          topic_ = getDefaultInstance().getTopic();
          onChanged();
          return this;
        }
        /**
         * <code>string topic = 1;</code>
         */
        public Builder setTopicBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          topic_ = value;
          onChanged();
          return this;
        }

        private long timestamp_ ;
        /**
         * <code>int64 timestamp = 2;</code>
         */
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>int64 timestamp = 2;</code>
         */
        public Builder setTimestamp(long value) {
          
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 timestamp = 2;</code>
         */
        public Builder clearTimestamp() {
          
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        private int partition_ ;
        /**
         * <code>int32 partition = 3;</code>
         */
        public int getPartition() {
          return partition_;
        }
        /**
         * <code>int32 partition = 3;</code>
         */
        public Builder setPartition(int value) {
          
          partition_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 partition = 3;</code>
         */
        public Builder clearPartition() {
          
          partition_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.ziggurat.proto.MessagePayload.Metadata)
      }

      // @@protoc_insertion_point(class_scope:com.ziggurat.proto.MessagePayload.Metadata)
      private static final com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata();
      }

      public static com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Metadata>
          PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
        public Metadata parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metadata(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Metadata> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Metadata> getParserForType() {
        return PARSER;
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 1;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int TOPIC_ENTITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object topicEntity_;
    /**
     * <code>string topic_entity = 2;</code>
     */
    public java.lang.String getTopicEntity() {
      java.lang.Object ref = topicEntity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicEntity_ = s;
        return s;
      }
    }
    /**
     * <code>string topic_entity = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicEntityBytes() {
      java.lang.Object ref = topicEntity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicEntity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETRY_COUNT_FIELD_NUMBER = 3;
    private int retryCount_;
    /**
     * <code>int32 retry_count = 3;</code>
     */
    public int getRetryCount() {
      return retryCount_;
    }

    public static final int METADATA_FIELD_NUMBER = 4;
    private com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata metadata_;
    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    public boolean hasMetadata() {
      return metadata_ != null;
    }
    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getMetadata() {
      return metadata_ == null ? com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.getDefaultInstance() : metadata_;
    }
    /**
     * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
     */
    public com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder getMetadataOrBuilder() {
      return getMetadata();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!message_.isEmpty()) {
        output.writeBytes(1, message_);
      }
      if (!getTopicEntityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicEntity_);
      }
      if (retryCount_ != 0) {
        output.writeInt32(3, retryCount_);
      }
      if (metadata_ != null) {
        output.writeMessage(4, getMetadata());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      if (!getTopicEntityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicEntity_);
      }
      if (retryCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, retryCount_);
      }
      if (metadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMetadata());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload)) {
        return super.equals(obj);
      }
      com.ziggurat.proto.MessagePayloadProto.MessagePayload other = (com.ziggurat.proto.MessagePayloadProto.MessagePayload) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getTopicEntity()
          .equals(other.getTopicEntity());
      result = result && (getRetryCount()
          == other.getRetryCount());
      result = result && (hasMetadata() == other.hasMetadata());
      if (hasMetadata()) {
        result = result && getMetadata()
            .equals(other.getMetadata());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TOPIC_ENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getTopicEntity().hashCode();
      hash = (37 * hash) + RETRY_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRetryCount();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ziggurat.proto.MessagePayloadProto.MessagePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ziggurat.proto.MessagePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ziggurat.proto.MessagePayload)
        com.ziggurat.proto.MessagePayloadProto.MessagePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ziggurat.proto.MessagePayloadProto.MessagePayload.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Builder.class);
      }

      // Construct using com.ziggurat.proto.MessagePayloadProto.MessagePayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;

        topicEntity_ = "";

        retryCount_ = 0;

        if (metadataBuilder_ == null) {
          metadata_ = null;
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstanceForType() {
        return com.ziggurat.proto.MessagePayloadProto.MessagePayload.getDefaultInstance();
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload build() {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload buildPartial() {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload result = new com.ziggurat.proto.MessagePayloadProto.MessagePayload(this);
        result.message_ = message_;
        result.topicEntity_ = topicEntity_;
        result.retryCount_ = retryCount_;
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload) {
          return mergeFrom((com.ziggurat.proto.MessagePayloadProto.MessagePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ziggurat.proto.MessagePayloadProto.MessagePayload other) {
        if (other == com.ziggurat.proto.MessagePayloadProto.MessagePayload.getDefaultInstance()) return this;
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        if (!other.getTopicEntity().isEmpty()) {
          topicEntity_ = other.topicEntity_;
          onChanged();
        }
        if (other.getRetryCount() != 0) {
          setRetryCount(other.getRetryCount());
        }
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ziggurat.proto.MessagePayloadProto.MessagePayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes message = 1;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>bytes message = 1;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private java.lang.Object topicEntity_ = "";
      /**
       * <code>string topic_entity = 2;</code>
       */
      public java.lang.String getTopicEntity() {
        java.lang.Object ref = topicEntity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topicEntity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicEntityBytes() {
        java.lang.Object ref = topicEntity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topicEntity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder setTopicEntity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topicEntity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder clearTopicEntity() {
        
        topicEntity_ = getDefaultInstance().getTopicEntity();
        onChanged();
        return this;
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder setTopicEntityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topicEntity_ = value;
        onChanged();
        return this;
      }

      private int retryCount_ ;
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public int getRetryCount() {
        return retryCount_;
      }
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public Builder setRetryCount(int value) {
        
        retryCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public Builder clearRetryCount() {
        
        retryCount_ = 0;
        onChanged();
        return this;
      }

      private com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata metadata_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder, com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder> metadataBuilder_;
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public boolean hasMetadata() {
        return metadataBuilder_ != null || metadata_ != null;
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public Builder setMetadata(com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
          onChanged();
        } else {
          metadataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public Builder setMetadata(
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
          onChanged();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public Builder mergeMetadata(com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata value) {
        if (metadataBuilder_ == null) {
          if (metadata_ != null) {
            metadata_ =
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
          } else {
            metadata_ = value;
          }
          onChanged();
        } else {
          metadataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = null;
          onChanged();
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder getMetadataBuilder() {
        
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      public com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>.com.ziggurat.proto.MessagePayload.Metadata metadata = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder, com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Metadata.Builder, com.ziggurat.proto.MessagePayloadProto.MessagePayload.MetadataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ziggurat.proto.MessagePayload)
    }

    // @@protoc_insertion_point(class_scope:com.ziggurat.proto.MessagePayload)
    private static final com.ziggurat.proto.MessagePayloadProto.MessagePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ziggurat.proto.MessagePayloadProto.MessagePayload();
    }

    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePayload>
        PARSER = new com.google.protobuf.AbstractParser<MessagePayload>() {
      public MessagePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagePayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessagePayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessagePayload> getParserForType() {
      return PARSER;
    }

    public com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ziggurat_proto_MessagePayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ziggurat_proto_MessagePayload_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/message-payload.proto\022\022com.ziggu" +
      "rat.proto\"\314\001\n\016MessagePayload\022\017\n\007message\030" +
      "\001 \001(\014\022\024\n\014topic_entity\030\002 \001(\t\022\023\n\013retry_cou" +
      "nt\030\003 \001(\005\022=\n\010metadata\030\004 \001(\0132+.com.ziggura" +
      "t.proto.MessagePayload.Metadata\032?\n\010Metad" +
      "ata\022\r\n\005topic\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022\021\n" +
      "\tpartition\030\003 \001(\005B)\n\022com.ziggurat.protoB\023" +
      "MessagePayloadProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ziggurat_proto_MessagePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ziggurat_proto_MessagePayload_descriptor,
        new java.lang.String[] { "Message", "TopicEntity", "RetryCount", "Metadata", });
    internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor =
      internal_static_com_ziggurat_proto_MessagePayload_descriptor.getNestedTypes().get(0);
    internal_static_com_ziggurat_proto_MessagePayload_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ziggurat_proto_MessagePayload_Metadata_descriptor,
        new java.lang.String[] { "Topic", "Timestamp", "Partition", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
