// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message-payload.proto

package com.ziggurat.proto;

public final class MessagePayloadProto {
  private MessagePayloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessagePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ziggurat.proto.MessagePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes message = 1;</code>
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>string topic_entity = 2;</code>
     */
    java.lang.String getTopicEntity();
    /**
     * <code>string topic_entity = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicEntityBytes();

    /**
     * <code>int32 retry_count = 3;</code>
     */
    int getRetryCount();
  }
  /**
   * Protobuf type {@code com.ziggurat.proto.MessagePayload}
   */
  public  static final class MessagePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ziggurat.proto.MessagePayload)
      MessagePayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessagePayload.newBuilder() to construct.
    private MessagePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessagePayload() {
      message_ = com.google.protobuf.ByteString.EMPTY;
      topicEntity_ = "";
      retryCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessagePayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              message_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topicEntity_ = s;
              break;
            }
            case 24: {

              retryCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ziggurat.proto.MessagePayloadProto.MessagePayload.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 1;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int TOPIC_ENTITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object topicEntity_;
    /**
     * <code>string topic_entity = 2;</code>
     */
    public java.lang.String getTopicEntity() {
      java.lang.Object ref = topicEntity_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicEntity_ = s;
        return s;
      }
    }
    /**
     * <code>string topic_entity = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicEntityBytes() {
      java.lang.Object ref = topicEntity_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicEntity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETRY_COUNT_FIELD_NUMBER = 3;
    private int retryCount_;
    /**
     * <code>int32 retry_count = 3;</code>
     */
    public int getRetryCount() {
      return retryCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!message_.isEmpty()) {
        output.writeBytes(1, message_);
      }
      if (!getTopicEntityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicEntity_);
      }
      if (retryCount_ != 0) {
        output.writeInt32(3, retryCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      if (!getTopicEntityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicEntity_);
      }
      if (retryCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, retryCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload)) {
        return super.equals(obj);
      }
      com.ziggurat.proto.MessagePayloadProto.MessagePayload other = (com.ziggurat.proto.MessagePayloadProto.MessagePayload) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getTopicEntity()
          .equals(other.getTopicEntity());
      result = result && (getRetryCount()
          == other.getRetryCount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TOPIC_ENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getTopicEntity().hashCode();
      hash = (37 * hash) + RETRY_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRetryCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ziggurat.proto.MessagePayloadProto.MessagePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ziggurat.proto.MessagePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ziggurat.proto.MessagePayload)
        com.ziggurat.proto.MessagePayloadProto.MessagePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ziggurat.proto.MessagePayloadProto.MessagePayload.class, com.ziggurat.proto.MessagePayloadProto.MessagePayload.Builder.class);
      }

      // Construct using com.ziggurat.proto.MessagePayloadProto.MessagePayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;

        topicEntity_ = "";

        retryCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ziggurat.proto.MessagePayloadProto.internal_static_com_ziggurat_proto_MessagePayload_descriptor;
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstanceForType() {
        return com.ziggurat.proto.MessagePayloadProto.MessagePayload.getDefaultInstance();
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload build() {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ziggurat.proto.MessagePayloadProto.MessagePayload buildPartial() {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload result = new com.ziggurat.proto.MessagePayloadProto.MessagePayload(this);
        result.message_ = message_;
        result.topicEntity_ = topicEntity_;
        result.retryCount_ = retryCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ziggurat.proto.MessagePayloadProto.MessagePayload) {
          return mergeFrom((com.ziggurat.proto.MessagePayloadProto.MessagePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ziggurat.proto.MessagePayloadProto.MessagePayload other) {
        if (other == com.ziggurat.proto.MessagePayloadProto.MessagePayload.getDefaultInstance()) return this;
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        if (!other.getTopicEntity().isEmpty()) {
          topicEntity_ = other.topicEntity_;
          onChanged();
        }
        if (other.getRetryCount() != 0) {
          setRetryCount(other.getRetryCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ziggurat.proto.MessagePayloadProto.MessagePayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ziggurat.proto.MessagePayloadProto.MessagePayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes message = 1;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>bytes message = 1;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private java.lang.Object topicEntity_ = "";
      /**
       * <code>string topic_entity = 2;</code>
       */
      public java.lang.String getTopicEntity() {
        java.lang.Object ref = topicEntity_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topicEntity_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicEntityBytes() {
        java.lang.Object ref = topicEntity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topicEntity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder setTopicEntity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topicEntity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder clearTopicEntity() {
        
        topicEntity_ = getDefaultInstance().getTopicEntity();
        onChanged();
        return this;
      }
      /**
       * <code>string topic_entity = 2;</code>
       */
      public Builder setTopicEntityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topicEntity_ = value;
        onChanged();
        return this;
      }

      private int retryCount_ ;
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public int getRetryCount() {
        return retryCount_;
      }
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public Builder setRetryCount(int value) {
        
        retryCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retry_count = 3;</code>
       */
      public Builder clearRetryCount() {
        
        retryCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ziggurat.proto.MessagePayload)
    }

    // @@protoc_insertion_point(class_scope:com.ziggurat.proto.MessagePayload)
    private static final com.ziggurat.proto.MessagePayloadProto.MessagePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ziggurat.proto.MessagePayloadProto.MessagePayload();
    }

    public static com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessagePayload>
        PARSER = new com.google.protobuf.AbstractParser<MessagePayload>() {
      public MessagePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagePayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessagePayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessagePayload> getParserForType() {
      return PARSER;
    }

    public com.ziggurat.proto.MessagePayloadProto.MessagePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ziggurat_proto_MessagePayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025message-payload.proto\022\022com.ziggurat.pr" +
      "oto\"L\n\016MessagePayload\022\017\n\007message\030\001 \001(\014\022\024" +
      "\n\014topic_entity\030\002 \001(\t\022\023\n\013retry_count\030\003 \001(" +
      "\005B)\n\022com.ziggurat.protoB\023MessagePayloadP" +
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ziggurat_proto_MessagePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ziggurat_proto_MessagePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ziggurat_proto_MessagePayload_descriptor,
        new java.lang.String[] { "Message", "TopicEntity", "RetryCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
