// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/example.proto

package com.gojek.test.proto;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhotoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gojek.test.proto.Photo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <code>string path = 2;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>bytes image = 6;</code>
     */
    com.google.protobuf.ByteString getImage();
  }
  /**
   * Protobuf type {@code com.gojek.test.proto.Photo}
   */
  public  static final class Photo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gojek.test.proto.Photo)
      PhotoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Photo.newBuilder() to construct.
    private Photo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Photo() {
      id_ = 0;
      path_ = "";
      image_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Photo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 50: {

              image_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gojek.test.proto.Example.Photo.class, com.gojek.test.proto.Example.Photo.Builder.class);
    }

    public interface LabelOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.gojek.test.proto.Photo.Label)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string item = 1;</code>
       */
      java.lang.String getItem();
      /**
       * <code>string item = 1;</code>
       */
      com.google.protobuf.ByteString
          getItemBytes();

      /**
       * <code>bool exists = 2;</code>
       */
      boolean getExists();
    }
    /**
     * Protobuf type {@code com.gojek.test.proto.Photo.Label}
     */
    public  static final class Label extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.gojek.test.proto.Photo.Label)
        LabelOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Label.newBuilder() to construct.
      private Label(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Label() {
        item_ = "";
        exists_ = false;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Label(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                item_ = s;
                break;
              }
              case 16: {

                exists_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Label_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Label_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gojek.test.proto.Example.Photo.Label.class, com.gojek.test.proto.Example.Photo.Label.Builder.class);
      }

      public static final int ITEM_FIELD_NUMBER = 1;
      private volatile java.lang.Object item_;
      /**
       * <code>string item = 1;</code>
       */
      public java.lang.String getItem() {
        java.lang.Object ref = item_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          item_ = s;
          return s;
        }
      }
      /**
       * <code>string item = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemBytes() {
        java.lang.Object ref = item_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          item_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EXISTS_FIELD_NUMBER = 2;
      private boolean exists_;
      /**
       * <code>bool exists = 2;</code>
       */
      public boolean getExists() {
        return exists_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getItemBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, item_);
        }
        if (exists_ != false) {
          output.writeBool(2, exists_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getItemBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, item_);
        }
        if (exists_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, exists_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.gojek.test.proto.Example.Photo.Label)) {
          return super.equals(obj);
        }
        com.gojek.test.proto.Example.Photo.Label other = (com.gojek.test.proto.Example.Photo.Label) obj;

        boolean result = true;
        result = result && getItem()
            .equals(other.getItem());
        result = result && (getExists()
            == other.getExists());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItem().hashCode();
        hash = (37 * hash) + EXISTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getExists());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Label parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.gojek.test.proto.Example.Photo.Label prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.gojek.test.proto.Photo.Label}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.gojek.test.proto.Photo.Label)
          com.gojek.test.proto.Example.Photo.LabelOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Label_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Label_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.gojek.test.proto.Example.Photo.Label.class, com.gojek.test.proto.Example.Photo.Label.Builder.class);
        }

        // Construct using com.gojek.test.proto.Example.Photo.Label.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          item_ = "";

          exists_ = false;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Label_descriptor;
        }

        public com.gojek.test.proto.Example.Photo.Label getDefaultInstanceForType() {
          return com.gojek.test.proto.Example.Photo.Label.getDefaultInstance();
        }

        public com.gojek.test.proto.Example.Photo.Label build() {
          com.gojek.test.proto.Example.Photo.Label result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.gojek.test.proto.Example.Photo.Label buildPartial() {
          com.gojek.test.proto.Example.Photo.Label result = new com.gojek.test.proto.Example.Photo.Label(this);
          result.item_ = item_;
          result.exists_ = exists_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.gojek.test.proto.Example.Photo.Label) {
            return mergeFrom((com.gojek.test.proto.Example.Photo.Label)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.gojek.test.proto.Example.Photo.Label other) {
          if (other == com.gojek.test.proto.Example.Photo.Label.getDefaultInstance()) return this;
          if (!other.getItem().isEmpty()) {
            item_ = other.item_;
            onChanged();
          }
          if (other.getExists() != false) {
            setExists(other.getExists());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.gojek.test.proto.Example.Photo.Label parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.gojek.test.proto.Example.Photo.Label) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object item_ = "";
        /**
         * <code>string item = 1;</code>
         */
        public java.lang.String getItem() {
          java.lang.Object ref = item_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            item_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string item = 1;</code>
         */
        public com.google.protobuf.ByteString
            getItemBytes() {
          java.lang.Object ref = item_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            item_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string item = 1;</code>
         */
        public Builder setItem(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          item_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string item = 1;</code>
         */
        public Builder clearItem() {
          
          item_ = getDefaultInstance().getItem();
          onChanged();
          return this;
        }
        /**
         * <code>string item = 1;</code>
         */
        public Builder setItemBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          item_ = value;
          onChanged();
          return this;
        }

        private boolean exists_ ;
        /**
         * <code>bool exists = 2;</code>
         */
        public boolean getExists() {
          return exists_;
        }
        /**
         * <code>bool exists = 2;</code>
         */
        public Builder setExists(boolean value) {
          
          exists_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool exists = 2;</code>
         */
        public Builder clearExists() {
          
          exists_ = false;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.gojek.test.proto.Photo.Label)
      }

      // @@protoc_insertion_point(class_scope:com.gojek.test.proto.Photo.Label)
      private static final com.gojek.test.proto.Example.Photo.Label DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.gojek.test.proto.Example.Photo.Label();
      }

      public static com.gojek.test.proto.Example.Photo.Label getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Label>
          PARSER = new com.google.protobuf.AbstractParser<Label>() {
        public Label parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Label(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Label> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Label> getParserForType() {
        return PARSER;
      }

      public com.gojek.test.proto.Example.Photo.Label getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface AttrOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.gojek.test.proto.Photo.Attr)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>string val = 2;</code>
       */
      java.lang.String getVal();
      /**
       * <code>string val = 2;</code>
       */
      com.google.protobuf.ByteString
          getValBytes();
    }
    /**
     * Protobuf type {@code com.gojek.test.proto.Photo.Attr}
     */
    public  static final class Attr extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.gojek.test.proto.Photo.Attr)
        AttrOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Attr.newBuilder() to construct.
      private Attr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Attr() {
        key_ = "";
        val_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Attr(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                val_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Attr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Attr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gojek.test.proto.Example.Photo.Attr.class, com.gojek.test.proto.Example.Photo.Attr.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VAL_FIELD_NUMBER = 2;
      private volatile java.lang.Object val_;
      /**
       * <code>string val = 2;</code>
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          val_ = s;
          return s;
        }
      }
      /**
       * <code>string val = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!getValBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, val_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!getValBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, val_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.gojek.test.proto.Example.Photo.Attr)) {
          return super.equals(obj);
        }
        com.gojek.test.proto.Example.Photo.Attr other = (com.gojek.test.proto.Example.Photo.Attr) obj;

        boolean result = true;
        result = result && getKey()
            .equals(other.getKey());
        result = result && getVal()
            .equals(other.getVal());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Attr parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.gojek.test.proto.Example.Photo.Attr prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.gojek.test.proto.Photo.Attr}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.gojek.test.proto.Photo.Attr)
          com.gojek.test.proto.Example.Photo.AttrOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Attr_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Attr_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.gojek.test.proto.Example.Photo.Attr.class, com.gojek.test.proto.Example.Photo.Attr.Builder.class);
        }

        // Construct using com.gojek.test.proto.Example.Photo.Attr.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          key_ = "";

          val_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Attr_descriptor;
        }

        public com.gojek.test.proto.Example.Photo.Attr getDefaultInstanceForType() {
          return com.gojek.test.proto.Example.Photo.Attr.getDefaultInstance();
        }

        public com.gojek.test.proto.Example.Photo.Attr build() {
          com.gojek.test.proto.Example.Photo.Attr result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.gojek.test.proto.Example.Photo.Attr buildPartial() {
          com.gojek.test.proto.Example.Photo.Attr result = new com.gojek.test.proto.Example.Photo.Attr(this);
          result.key_ = key_;
          result.val_ = val_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.gojek.test.proto.Example.Photo.Attr) {
            return mergeFrom((com.gojek.test.proto.Example.Photo.Attr)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.gojek.test.proto.Example.Photo.Attr other) {
          if (other == com.gojek.test.proto.Example.Photo.Attr.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (!other.getVal().isEmpty()) {
            val_ = other.val_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.gojek.test.proto.Example.Photo.Attr parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.gojek.test.proto.Example.Photo.Attr) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object val_ = "";
        /**
         * <code>string val = 2;</code>
         */
        public java.lang.String getVal() {
          java.lang.Object ref = val_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            val_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string val = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValBytes() {
          java.lang.Object ref = val_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            val_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string val = 2;</code>
         */
        public Builder setVal(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          val_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string val = 2;</code>
         */
        public Builder clearVal() {
          
          val_ = getDefaultInstance().getVal();
          onChanged();
          return this;
        }
        /**
         * <code>string val = 2;</code>
         */
        public Builder setValBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          val_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.gojek.test.proto.Photo.Attr)
      }

      // @@protoc_insertion_point(class_scope:com.gojek.test.proto.Photo.Attr)
      private static final com.gojek.test.proto.Example.Photo.Attr DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.gojek.test.proto.Example.Photo.Attr();
      }

      public static com.gojek.test.proto.Example.Photo.Attr getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Attr>
          PARSER = new com.google.protobuf.AbstractParser<Attr>() {
        public Attr parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Attr(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Attr> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Attr> getParserForType() {
        return PARSER;
      }

      public com.gojek.test.proto.Example.Photo.Attr getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface TagOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.gojek.test.proto.Photo.Tag)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 person_id = 1;</code>
       */
      int getPersonId();

      /**
       * <code>int32 y_coord = 3;</code>
       */
      int getYCoord();

      /**
       * <code>int32 width = 4;</code>
       */
      int getWidth();

      /**
       * <code>int32 height = 5;</code>
       */
      int getHeight();
    }
    /**
     * Protobuf type {@code com.gojek.test.proto.Photo.Tag}
     */
    public  static final class Tag extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.gojek.test.proto.Photo.Tag)
        TagOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Tag.newBuilder() to construct.
      private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Tag() {
        personId_ = 0;
        yCoord_ = 0;
        width_ = 0;
        height_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Tag(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                personId_ = input.readInt32();
                break;
              }
              case 24: {

                yCoord_ = input.readInt32();
                break;
              }
              case 32: {

                width_ = input.readInt32();
                break;
              }
              case 40: {

                height_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Tag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gojek.test.proto.Example.Photo.Tag.class, com.gojek.test.proto.Example.Photo.Tag.Builder.class);
      }

      public static final int PERSON_ID_FIELD_NUMBER = 1;
      private int personId_;
      /**
       * <code>int32 person_id = 1;</code>
       */
      public int getPersonId() {
        return personId_;
      }

      public static final int Y_COORD_FIELD_NUMBER = 3;
      private int yCoord_;
      /**
       * <code>int32 y_coord = 3;</code>
       */
      public int getYCoord() {
        return yCoord_;
      }

      public static final int WIDTH_FIELD_NUMBER = 4;
      private int width_;
      /**
       * <code>int32 width = 4;</code>
       */
      public int getWidth() {
        return width_;
      }

      public static final int HEIGHT_FIELD_NUMBER = 5;
      private int height_;
      /**
       * <code>int32 height = 5;</code>
       */
      public int getHeight() {
        return height_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (personId_ != 0) {
          output.writeInt32(1, personId_);
        }
        if (yCoord_ != 0) {
          output.writeInt32(3, yCoord_);
        }
        if (width_ != 0) {
          output.writeInt32(4, width_);
        }
        if (height_ != 0) {
          output.writeInt32(5, height_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (personId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, personId_);
        }
        if (yCoord_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, yCoord_);
        }
        if (width_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, width_);
        }
        if (height_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, height_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.gojek.test.proto.Example.Photo.Tag)) {
          return super.equals(obj);
        }
        com.gojek.test.proto.Example.Photo.Tag other = (com.gojek.test.proto.Example.Photo.Tag) obj;

        boolean result = true;
        result = result && (getPersonId()
            == other.getPersonId());
        result = result && (getYCoord()
            == other.getYCoord());
        result = result && (getWidth()
            == other.getWidth());
        result = result && (getHeight()
            == other.getHeight());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPersonId();
        hash = (37 * hash) + Y_COORD_FIELD_NUMBER;
        hash = (53 * hash) + getYCoord();
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.gojek.test.proto.Example.Photo.Tag parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.gojek.test.proto.Example.Photo.Tag prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.gojek.test.proto.Photo.Tag}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.gojek.test.proto.Photo.Tag)
          com.gojek.test.proto.Example.Photo.TagOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Tag_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Tag_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.gojek.test.proto.Example.Photo.Tag.class, com.gojek.test.proto.Example.Photo.Tag.Builder.class);
        }

        // Construct using com.gojek.test.proto.Example.Photo.Tag.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          personId_ = 0;

          yCoord_ = 0;

          width_ = 0;

          height_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_Tag_descriptor;
        }

        public com.gojek.test.proto.Example.Photo.Tag getDefaultInstanceForType() {
          return com.gojek.test.proto.Example.Photo.Tag.getDefaultInstance();
        }

        public com.gojek.test.proto.Example.Photo.Tag build() {
          com.gojek.test.proto.Example.Photo.Tag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.gojek.test.proto.Example.Photo.Tag buildPartial() {
          com.gojek.test.proto.Example.Photo.Tag result = new com.gojek.test.proto.Example.Photo.Tag(this);
          result.personId_ = personId_;
          result.yCoord_ = yCoord_;
          result.width_ = width_;
          result.height_ = height_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.gojek.test.proto.Example.Photo.Tag) {
            return mergeFrom((com.gojek.test.proto.Example.Photo.Tag)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.gojek.test.proto.Example.Photo.Tag other) {
          if (other == com.gojek.test.proto.Example.Photo.Tag.getDefaultInstance()) return this;
          if (other.getPersonId() != 0) {
            setPersonId(other.getPersonId());
          }
          if (other.getYCoord() != 0) {
            setYCoord(other.getYCoord());
          }
          if (other.getWidth() != 0) {
            setWidth(other.getWidth());
          }
          if (other.getHeight() != 0) {
            setHeight(other.getHeight());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.gojek.test.proto.Example.Photo.Tag parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.gojek.test.proto.Example.Photo.Tag) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int personId_ ;
        /**
         * <code>int32 person_id = 1;</code>
         */
        public int getPersonId() {
          return personId_;
        }
        /**
         * <code>int32 person_id = 1;</code>
         */
        public Builder setPersonId(int value) {
          
          personId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 person_id = 1;</code>
         */
        public Builder clearPersonId() {
          
          personId_ = 0;
          onChanged();
          return this;
        }

        private int yCoord_ ;
        /**
         * <code>int32 y_coord = 3;</code>
         */
        public int getYCoord() {
          return yCoord_;
        }
        /**
         * <code>int32 y_coord = 3;</code>
         */
        public Builder setYCoord(int value) {
          
          yCoord_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 y_coord = 3;</code>
         */
        public Builder clearYCoord() {
          
          yCoord_ = 0;
          onChanged();
          return this;
        }

        private int width_ ;
        /**
         * <code>int32 width = 4;</code>
         */
        public int getWidth() {
          return width_;
        }
        /**
         * <code>int32 width = 4;</code>
         */
        public Builder setWidth(int value) {
          
          width_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 width = 4;</code>
         */
        public Builder clearWidth() {
          
          width_ = 0;
          onChanged();
          return this;
        }

        private int height_ ;
        /**
         * <code>int32 height = 5;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>int32 height = 5;</code>
         */
        public Builder setHeight(int value) {
          
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 height = 5;</code>
         */
        public Builder clearHeight() {
          
          height_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.gojek.test.proto.Photo.Tag)
      }

      // @@protoc_insertion_point(class_scope:com.gojek.test.proto.Photo.Tag)
      private static final com.gojek.test.proto.Example.Photo.Tag DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.gojek.test.proto.Example.Photo.Tag();
      }

      public static com.gojek.test.proto.Example.Photo.Tag getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Tag>
          PARSER = new com.google.protobuf.AbstractParser<Tag>() {
        public Tag parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Tag(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Tag> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Tag> getParserForType() {
        return PARSER;
      }

      public com.gojek.test.proto.Example.Photo.Tag getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object path_;
    /**
     * <code>string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString image_;
    /**
     * <code>bytes image = 6;</code>
     */
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      if (!image_.isEmpty()) {
        output.writeBytes(6, image_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      if (!image_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, image_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gojek.test.proto.Example.Photo)) {
        return super.equals(obj);
      }
      com.gojek.test.proto.Example.Photo other = (com.gojek.test.proto.Example.Photo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getPath()
          .equals(other.getPath());
      result = result && getImage()
          .equals(other.getImage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gojek.test.proto.Example.Photo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gojek.test.proto.Example.Photo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gojek.test.proto.Example.Photo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gojek.test.proto.Example.Photo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gojek.test.proto.Example.Photo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gojek.test.proto.Photo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gojek.test.proto.Photo)
        com.gojek.test.proto.Example.PhotoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gojek.test.proto.Example.Photo.class, com.gojek.test.proto.Example.Photo.Builder.class);
      }

      // Construct using com.gojek.test.proto.Example.Photo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        path_ = "";

        image_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gojek.test.proto.Example.internal_static_com_gojek_test_proto_Photo_descriptor;
      }

      public com.gojek.test.proto.Example.Photo getDefaultInstanceForType() {
        return com.gojek.test.proto.Example.Photo.getDefaultInstance();
      }

      public com.gojek.test.proto.Example.Photo build() {
        com.gojek.test.proto.Example.Photo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gojek.test.proto.Example.Photo buildPartial() {
        com.gojek.test.proto.Example.Photo result = new com.gojek.test.proto.Example.Photo(this);
        result.id_ = id_;
        result.path_ = path_;
        result.image_ = image_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gojek.test.proto.Example.Photo) {
          return mergeFrom((com.gojek.test.proto.Example.Photo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gojek.test.proto.Example.Photo other) {
        if (other == com.gojek.test.proto.Example.Photo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (other.getImage() != com.google.protobuf.ByteString.EMPTY) {
          setImage(other.getImage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gojek.test.proto.Example.Photo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gojek.test.proto.Example.Photo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 2;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 2;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string path = 2;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes image = 6;</code>
       */
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      /**
       * <code>bytes image = 6;</code>
       */
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes image = 6;</code>
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gojek.test.proto.Photo)
    }

    // @@protoc_insertion_point(class_scope:com.gojek.test.proto.Photo)
    private static final com.gojek.test.proto.Example.Photo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gojek.test.proto.Example.Photo();
    }

    public static com.gojek.test.proto.Example.Photo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Photo>
        PARSER = new com.google.protobuf.AbstractParser<Photo>() {
      public Photo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Photo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Photo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Photo> getParserForType() {
      return PARSER;
    }

    public com.gojek.test.proto.Example.Photo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gojek_test_proto_Photo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gojek_test_proto_Photo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gojek_test_proto_Photo_Label_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gojek_test_proto_Photo_Label_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gojek_test_proto_Photo_Attr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gojek_test_proto_Photo_Attr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gojek_test_proto_Photo_Tag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gojek_test_proto_Photo_Tag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/example.proto\022\024com.gojek.test.pr" +
      "oto\"\303\001\n\005Photo\022\n\n\002id\030\001 \001(\005\022\014\n\004path\030\002 \001(\t\022" +
      "\r\n\005image\030\006 \001(\014\032%\n\005Label\022\014\n\004item\030\001 \001(\t\022\016\n" +
      "\006exists\030\002 \001(\010\032 \n\004Attr\022\013\n\003key\030\001 \001(\t\022\013\n\003va" +
      "l\030\002 \001(\t\032H\n\003Tag\022\021\n\tperson_id\030\001 \001(\005\022\017\n\007y_c" +
      "oord\030\003 \001(\005\022\r\n\005width\030\004 \001(\005\022\016\n\006height\030\005 \001(" +
      "\005B\037\n\024com.gojek.test.protoB\007Exampleb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gojek_test_proto_Photo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gojek_test_proto_Photo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gojek_test_proto_Photo_descriptor,
        new java.lang.String[] { "Id", "Path", "Image", });
    internal_static_com_gojek_test_proto_Photo_Label_descriptor =
      internal_static_com_gojek_test_proto_Photo_descriptor.getNestedTypes().get(0);
    internal_static_com_gojek_test_proto_Photo_Label_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gojek_test_proto_Photo_Label_descriptor,
        new java.lang.String[] { "Item", "Exists", });
    internal_static_com_gojek_test_proto_Photo_Attr_descriptor =
      internal_static_com_gojek_test_proto_Photo_descriptor.getNestedTypes().get(1);
    internal_static_com_gojek_test_proto_Photo_Attr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gojek_test_proto_Photo_Attr_descriptor,
        new java.lang.String[] { "Key", "Val", });
    internal_static_com_gojek_test_proto_Photo_Tag_descriptor =
      internal_static_com_gojek_test_proto_Photo_descriptor.getNestedTypes().get(2);
    internal_static_com_gojek_test_proto_Photo_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gojek_test_proto_Photo_Tag_descriptor,
        new java.lang.String[] { "PersonId", "YCoord", "Width", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
