name: send-update-event

on:
  workflow_dispatch:

jobs:
  send_update_event:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{secrets.GH_TOKEN}}
        repository: gojek/ziggurat-web
        event-type: ziggurat-release-event